version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    # Use POSTGRES_USER from .env
    env_file: .env

  webapp:
    build:
      context: .
      dockerfile: ./compose/webapp/Dockerfile-dev
    command: python /app/manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    # Use POSTGRES_USER from .env
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres





